config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
resources :reviews do
  #this is a shortcut to get it to set up: create, new, show, index, etc that we used for the controller.
  #we would have it be separate instead of nested under via "do" if it was totally unrelated (eg. posts or jobs)

resources :comments


resource :bookmark

end

resources :users

resources :bookmarks

resource :session

resource :account 

get "about", to: "pages#about"

root "pages#home"



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  #check if logged in
  before_action :check_login, except: [:index, :show]

def index
  # this is our list page for our reviews

#variable is something that always changes. we want it to equal to some random number. The "@" indicates the variable
#we want to pull this variable into our HTML

  @price = params[:price]
  @cuisine = params[:cuisine]
  @location = params[:location]
  #find parameters from URL

#start with all the Reviews
@reviews= Review.all

#filtering by price
if @price.present?
  @reviews= @reviews.where(price: @price)
  #replace all the reviews with reviews where the COLUMN price is the parameter of the URL price
end

#filter by Cuisine
if @cuisine.present?
  @reviews= @reviews.where(cuisine: @cuisine)
end

#filtering by location
if @location.present?
  @reviews= @reviews.near(@location)
end


end





def new
  #new is the FORM for adding a new review, not actaully adding it into database
  #def means it's a function
  #need to have an end whenever we have a def
  @review = Review.new
  #get our Review database, and make a new review
  #take our controller, make a new model, and give it to our HTML to add a form to it
end




def create
  #this will take the info from the form and add it to the model
  @review = Review.new(form_params)


  #and then associate it wiht a user
  @review.user = @current_user

#we want to check if the model can be saved
#if it is, we're going to the home page again
#if it isn't, show the new form

if @review.save
  redirect_to root_path
else
  #show the view for new.html.erb
  render "new"

end



end



def show
  #this leads us to an individual review page
@review = Review.find(params[:id])
end



def destroy
  #find the indivial review
  @review = Review.find(params[:id])


  #then we want to destroy it (if they CAN destroy it or have access)
  if @review.user == @current_user
  @review.destroy
    #redirect to homepage
  redirect_to root_path
end
end



def edit
  #find the individual review and put it into the form
  @review = Review.find(params[:id])

#if not the review user, even if access via URL will be redirected to homepage
  if @review.user != @current_user
    redirect_to root_path
  elsif @review.created_at < 1.hour.ago
    redirect_to review_path(@review)
    #elsif
  end
end



def update
#find the individla review
  @review = Review.find(params[:id])
#update with the new info from the form


if @review.user != @current_user
  redirect_to root_path
else

    if @review.update(form_params)
  #redirect somewhere new
    redirect_to review_path(@review)
  else

    render "edit"

    end
end

end


def form_params
  #we can use this within rails and any part of this ReviewsController
  #like a variable/ const in Javascript or a shortcut
  (params.require(:review).permit(:title, :body, :score, :restaurant, :ambiance, :cuisine, :price, :address, :photo))
end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>

<%= f.input :title %>
<%= f.input :restaurant%>
<%= f.input :address %>
<%= f.input :photo %>
<%= f.input :ambiance, collection: ["Casual", "Date Night", "Fast Food", "Family-Friendly", "Fancy"] %>
<%= f.input :cuisine, collection: ["Japanese", "Mexican", "American"] %>
<%= f.input :price, as: :radio_buttons, collection: [1, 2, 3, 4]%>
<%= f.input :body %>
<%= f.input :score, collection: 1..10 %>


<%= f.button :submit%>

<% end %>

app/views/reviews/edit.html.erb
<h3>Edit your new review</h3>
<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
<div>
  <%= active_link_to "  All Restaurants  ", root_path, active: {price: nil, cuisine: nil, location:nil } %>
  <%= active_link_to "  $  ", root_path(price: 1, cuisine: @cuisine, location: @location), active: { price: 1 }%>
  <%= active_link_to "  $$  ", root_path(price: 2, cuisine: @cuisine, location: @location), active: { price: 2 }%>
    <%= active_link_to "  $$$  ", root_path(price: 3, cuisine: @cuisine, location: @location), active: { price: 3 }%>
      <%= active_link_to "  $$$$  ", root_path(price: 4, cuisine: @cuisine, location: @location), active: { price: 4 }%>
</div>
<div>

      <%= active_link_to "  Japanese  ", root_path(cuisine: "Japanese", price: @price, location: @location), active: { cuisine: "Japanese" } %>
            <%= active_link_to "  Italian  ", root_path(cuisine: "Italian",  price: @price, location: @location), active: { cuisine: "Italian" } %>

</div>

<form action="/">
  <input field="text" name="location"
  placeholder="Search Location..." value= "<%= @location %>">

  <input type="hidden" name="price" value="<%= @price %>">
    <input type="hidden" name="cuisine" value="<%= @cuisine %>">
  </form>

  </nav>





<% @reviews. each do |review| %>

  <div class="review">
    <%= link_to review_path(review) do %>

        <%= image_tag review.photo.medium.url %>

    <h2> <%= review.title %> </h2>
    <p> <%= review.cuisine %> -
    <%= pluralize review.comments.count, "comment" %> </p>
    <% end %>
  </div>
  <% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new Review" %>

<h3>Add your new review</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<%= image_tag @review.photo.medium.url %>

<h1><%= @review.title %></h1>
<h2><%= simple_format @review.restaurant %></h2>

<% if is_logged_in? %>
<p>

<% if @review.bookmarks.where(user: @current_user).any? %>
<%= link_to "Unfavourite 💔", review_bookmark_path(@review), method: :delete %>
<% else %>
  <%= link_to "Favourite 🖤 ", review_bookmark_path(@review), method: :post %>
<% end %>
</p>
<% end %>


<h3>Bookmarked by...</h3>
<ul>
  <% @review.bookmarks.each do |bookmark| %>
  <li> <%= bookmark.user.username %></li>
  <% end %>
  </ul>



<div class="score">
<%= @review.score %>/ 10 </div>


<div class="user">
  Posted by
  <% if @review.user.present? %>
  <%= link_to @review.user.username, user_path(@review.user)  %>
  <% else %>
  Anonymous
  <% end %>
  </div>


<div class="ambiance"> <% if @review.ambiance.present? %>Ambiance:<%= simple_format @review.ambiance %> </div>
<% end %>

<div class="Cuisine">Cuisine:<%= simple_format @review.cuisine %></div>

  <div class="Price">Price:<%= @review.price %></div>

  <div class="body">
    <%= simple_format @review.body %></div>



<% if @review.user == @current_user %>
<% if @review.created_at > 1.hour.ago %>
    <div class="actions">
      <%= link_to "Edit this Review", edit_review_path(@review)%>
      <% end %>
      <%= link_to "Delete this Review", review_path(@review), method: :delete, data: { confirm: "Are you sure?" }%>
      </div>
<% end %>



<h3> Comments </h3>
<% @review.comments.order("created_at desc").each do |comment| %>
<div class="comment">
  <%= simple_format comment.body %>
  <p class= "posted"> Posted <%= time_ago_in_words comment.created_at %> ago
    by
    <% if comment.user.present? %>
     <%= link_to comment.user.username, user_path(comment.user) %>
   <% else %>
 anonymous
<% end %>
</p>
  </div>
<% end %>


<% if is_logged_in? %>
  <h3>Add a comment</h3>
<%= simple_form_for [@review, Comment.new] do |f| %>
<%= f.input :body %>
<%= f.button :submit %>
<% end %>
<% end %>