config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
resources :reviews do
  #this is a shortcut to get it to set up: create, new, show, index, etc that we used for the controller.
  #we would have it be separate instead of nested under via "do" if it was totally unrelated (eg. posts or jobs)

resources :comments


resource :bookmark

end

resources :users

resources :bookmarks

resource :session

resource :account 

get "about", to: "pages#about"

root "pages#home"



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
  <h1>
    <%= link_to root_path do%>
    <%= image_tag "bien_logo.svg" %>
    <% end %>
  </h1>


<nav>
<% if is_logged_in? %>
<%= @current_user.username %> |
<% end %>
  <%= link_to "List of Reviews", reviews_path %> |
  <% if is_logged_in? %>
<% if @current_user.is_admin? %>
<%= link_to "Admin Panel", admin_root_path %> |
<% end %>
  <%= link_to "Add a review", new_review_path %> |
  <%= link_to "Your Favourites", bookmarks_path %> |
  <%= link_to "Edit Account", edit_account_path %> |
  <%= link_to "Log out", session_path, method: :delete %>
  <% else %>
  <%= link_to "Sign up", new_user_path %> |
  <%= link_to "Log in", new_session_path %>
  <% end %>
  </nav>
    </header>

<%if flash[:success].present? %>
<div class="success">
  <%= flash[:success] %>
  </div>
  <% end %>


<main>
    <%= yield %>
</main>

    <footer>
      Copyright 2017 Bien ReviewsController | <%= link_to "About", about_path %>
      </footer>
  </body>
</html>